"""
Hand-built movement scenarios targeting the rare paths real games barely reach.

The full-turn traces (dump_turn_traces.py) cover ordinary play well - 103 of 180
turns contain a battle - but they give no evidence about the specific edge cases
that make movement.py the trickiest module to port:

  - Line Battle tie-breaks, including the EXACT-TIE coin flip, the only place a
    movement step consumes rng at all.
  - Overstacked peaceful merges reverting, and the two documented quirks in
    _revert_departure: reverting onto an origin another faction has since claimed
    (starts a battle there) and onto an origin an unrelated battle locked this
    same step (recreates a peaceful army on a locked hex).
  - Walking onto an undefended foreign capital or outpost, which now always forces
    a battle.
  - Reinforcing an already-locked hex, and pushing toward MAX_BATTLE_CONTRIB.

Each scenario is a hand-placed board, one movement step, and the resulting state -
generated by engine_old, replayed by the C++ engine.

Usage:  python engine/tools/dump_movement_scenarios.py > engine/tests/data/movement_scenarios.txt
"""

import copy
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _bootstrap  # noqa: E402

_bootstrap.install()

from engine.movement import apply_movement_step  # noqa: E402
from engine.setup import create_initial_state  # noqa: E402
from engine.state import NO_FACTION  # noqa: E402

from state_io import write_state  # noqa: E402

RADIUS = 5
NUM_FACTIONS = 6
IMPASSABLE = (1, 2)  # mountain, lake


def blank_state(seed=7, terrain_flat=True):
    """A generated board with everything but terrain cleared. terrain_flat makes
    every hex plains, so scenarios can place armies anywhere without tripping over
    impassable tiles; scenarios that care about terrain set it explicitly."""
    s = create_initial_state(radius=RADIUS, num_factions=NUM_FACTIONS, seed=seed)
    if terrain_flat:
        s.terrain[:] = 0
    s.city_owner[:] = NO_FACTION
    s.is_capital[:] = False
    s.city_placer[:] = NO_FACTION
    s.army_faction[:] = NO_FACTION
    s.army_units[:] = 0
    s.frozen[:] = False
    s.locked[:] = False
    s.gold[:] = 0
    s.kill_xp[:] = 0
    return s


def put(s, hex_index, faction, inf=0, cav=0, arc=0):
    s.army_faction[hex_index] = faction
    s.army_units[hex_index] = [inf, cav, arc]


def nb(s, hex_index, direction):
    return int(s.grid.neighbor_table[hex_index, direction])


def find_chain(s, length):
    """A run of `length` hexes each adjacent to the next, all passable."""
    for start in range(s.num_hexes):
        for d in range(6):
            chain = [start]
            cur = start
            ok = True
            for _ in range(length - 1):
                nxt = nb(s, cur, d)
                if nxt < 0 or s.terrain[nxt] in IMPASSABLE:
                    ok = False
                    break
                chain.append(nxt)
                cur = nxt
            if ok and len(chain) == length and s.terrain[chain[0]] not in IMPASSABLE:
                return chain, d
    raise RuntimeError("no chain found")


def find_hub(s, spokes):
    """A hex with at least `spokes` passable neighbours; returns (hub, [(nbr, dir_to_hub)])."""
    for h in range(s.num_hexes):
        if s.terrain[h] in IMPASSABLE:
            continue
        found = []
        for d in range(6):
            j = nb(s, h, d)
            if j >= 0 and s.terrain[j] not in IMPASSABLE:
                back = None
                for d2 in range(6):
                    if nb(s, j, d2) == h:
                        back = d2
                if back is not None:
                    found.append((j, back))
        if len(found) >= spokes:
            return h, found[:spokes]
    raise RuntimeError("no hub found")


SCENARIOS = []


def scenario(name, cavalry_only=False, seeds=(1,)):
    def deco(fn):
        for seed in seeds:
            SCENARIOS.append((f"{name}#s{seed}", fn, cavalry_only, seed))
        return fn
    return deco


# --- Line Battles -----------------------------------------------------------

# Exact tie: the battle hex is decided by rng.random() < 0.5, the ONLY rng draw a
# movement step ever makes. Several seeds so both branches are taken.
@scenario("line_battle_tie", seeds=(1, 2, 3, 4, 5, 6))
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=3)
    put(s, b, 1, inf=3)
    back = next(d2 for d2 in range(6) if nb(s, b, d2) == a)
    return {0: (a, d), 1: (b, back)}


# Unequal armies: the SMALLER army's own hex hosts the fight. Both orderings, so a
# tie-break implemented backwards cannot pass by luck.
@scenario("line_battle_smaller_first")
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=1)
    put(s, b, 1, inf=5)
    back = next(d2 for d2 in range(6) if nb(s, b, d2) == a)
    return {0: (a, d), 1: (b, back)}


@scenario("line_battle_larger_first")
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=5)
    put(s, b, 1, inf=1)
    back = next(d2 for d2 in range(6) if nb(s, b, d2) == a)
    return {0: (a, d), 1: (b, back)}


# --- Encounter battles ------------------------------------------------------

@scenario("encounter_three_factions")
def _(s):
    hub, spokes = find_hub(s, 3)
    actions = {}
    for i, (nbr, dir_to_hub) in enumerate(spokes):
        put(s, nbr, i, inf=2)
        actions[i] = (nbr, dir_to_hub)
    return actions


@scenario("encounter_then_reinforce_locked")
def _(s):
    """Two factions collide on the hub (locking it); a third arrives the same step
    from elsewhere and joins as a reinforcement."""
    hub, spokes = find_hub(s, 3)
    actions = {}
    for i, (nbr, dir_to_hub) in enumerate(spokes[:3]):
        put(s, nbr, i, inf=2, cav=1)
        actions[i] = (nbr, dir_to_hub)
    return actions


# --- Structures force a battle even undefended -------------------------------

@scenario("attack_undefended_capital")
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=4)
    s.city_owner[b] = 1
    s.is_capital[b] = True
    return {0: (a, d)}


@scenario("attack_undefended_outpost")
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=4)
    s.city_owner[b] = 1
    s.is_capital[b] = False
    return {0: (a, d)}


@scenario("move_onto_own_outpost_is_peaceful")
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=2)
    s.city_owner[b] = 0
    return {0: (a, d)}


# --- Overstacking and the revert quirks --------------------------------------

@scenario("overstack_revert_simple")
def _(s):
    """5 + 4 into one hex exceeds the 6-unit cap: the move is illegal and the
    arriving army goes home untouched."""
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=5)
    put(s, b, 0, inf=4)
    return {0: (a, d)}


@scenario("overstack_revert_multi_arrival")
def _(s):
    hub, spokes = find_hub(s, 3)
    actions = {}
    for i, (nbr, dir_to_hub) in enumerate(spokes[:3]):
        put(s, nbr, 0 if i == 0 else i, inf=3)
        actions[0 if i == 0 else i] = (nbr, dir_to_hub)
    put(s, hub, 0, inf=1)
    return actions


@scenario("revert_onto_origin_claimed_by_enemy")
def _(s):
    """QUIRK: faction 0 overstacks and reverts, but faction 1 peacefully moved
    into 0's origin the same step - so the revert starts a battle there."""
    chain, d = find_chain(s, 3)
    a, b, c = chain
    put(s, a, 0, inf=5)   # a -> b, will overstack and revert
    put(s, b, 0, inf=4)
    put(s, c, 1, inf=2)   # c -> b? no: 1 moves into a, which 0 is vacating
    back = next(d2 for d2 in range(6) if nb(s, b, d2) == a)
    s.army_faction[c] = NO_FACTION
    s.army_units[c] = 0
    put(s, b, 0, inf=4)
    # faction 1 sits on b's far side and steps into a
    put(s, c, 1, inf=2)
    return {0: (a, d), 1: (c, back)} if nb(s, c, back) == b else {0: (a, d)}


@scenario("revert_onto_own_origin_merges")
def _(s):
    """Faction 0 moves a cavalry-only stack out and an overstacked move reverts
    onto the same origin, merging with what stayed behind."""
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=6)
    put(s, b, 0, inf=3)
    return {0: (a, d)}


# --- Terrain interactions ----------------------------------------------------

@scenario("marsh_freezes_on_entry")
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    s.terrain[b] = 4  # marsh
    put(s, a, 0, inf=2)
    return {0: (a, d)}


@scenario("impassable_move_is_dropped")
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    s.terrain[b] = 1  # mountain
    put(s, a, 0, inf=2)
    return {0: (a, d)}


@scenario("frozen_army_cannot_move")
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=2)
    s.frozen[a] = True
    return {0: (a, d)}


@scenario("locked_army_cannot_move")
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=2)
    s.locked[a] = True
    s.battle_faction[a, 0] = 0
    s.battle_units[a, 0] = [2, 0, 0]
    s.battle_origin[a, 0] = a
    s.battle_order.append(a)
    s.army_faction[a] = NO_FACTION
    s.army_units[a] = 0
    return {0: (a, d)}


# --- Cavalry phase -----------------------------------------------------------

@scenario("cavalry_only_leaves_others_behind", cavalry_only=True)
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=2, cav=2, arc=1)
    return {0: (a, d)}


@scenario("cavalry_only_no_cavalry_is_dropped", cavalry_only=True)
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=3)
    return {0: (a, d)}


@scenario("cavalry_line_battle", cavalry_only=True, seeds=(1, 2, 3))
def _(s):
    chain, d = find_chain(s, 2)
    a, b = chain
    put(s, a, 0, inf=1, cav=2)
    put(s, b, 1, inf=1, cav=2)
    back = next(d2 for d2 in range(6) if nb(s, b, d2) == a)
    return {0: (a, d), 1: (b, back)}


# --- Many contributions into one hex ----------------------------------------

@scenario("six_factions_one_hex")
def _(s):
    hub, spokes = find_hub(s, 6)
    actions = {}
    for i, (nbr, dir_to_hub) in enumerate(spokes[:6]):
        put(s, nbr, i, inf=1, cav=1, arc=1)
        actions[i] = (nbr, dir_to_hub)
    return actions


def _clone(state):
    new = copy.copy(state)
    for field in ("terrain", "city_owner", "is_capital", "outpost_upgrade", "city_placer",
                  "capital_settle_order", "army_faction", "army_units", "frozen", "locked",
                  "battle_faction", "battle_origin", "battle_units", "battle_moved",
                  "battle_round", "gold", "resources", "kill_xp", "victory_points", "alive"):
        setattr(new, field, getattr(state, field).copy())
    new.battle_order = list(state.battle_order)
    return new


def main():
    out = sys.stdout
    out_cases = []
    for name, build, cavalry_only, seed in SCENARIOS:
        s = blank_state()
        actions = build(s)
        before = _clone(s)
        after = _clone(s)
        apply_movement_step(after, actions, random.Random(seed), cavalry_only=cavalry_only)
        out_cases.append((name, seed, cavalry_only, actions, before, after))

    out.write(f"SCENARIOS {len(out_cases)}\n")
    for name, seed, cavalry_only, actions, before, after in out_cases:
        out.write(f"SCENARIO {name}\n")
        out.write(f"SEED {seed}\n")
        out.write(f"CAVALRY_ONLY {1 if cavalry_only else 0}\n")
        items = [(f, a) for f, a in actions.items() if a is not None]
        out.write(f"ACTIONS {len(items)}\n")
        for faction, (hex_index, direction) in items:
            out.write(f"{faction} {int(hex_index)} {int(direction)}\n")
        write_state(out, before)
        write_state(out, after)


if __name__ == "__main__":
    main()
