"""
Step-by-step visualizer for engine/placement.py's colourless city
placement + capital draft (pygame).

Reads city_placement_log.json (written by run.py), a flat, ordered list
of every individual placement/draft step (see run_city_setup's
docstring for what each step type means). Unlike hex_gen_visualizer.py's
terrain generation - where the terrain itself doesn't exist yet at each
step - the board's terrain is already fully generated by the time this
phase runs, so the full terrain map ships in the log and is drawn as
static background from the start; only the city icons build up step by
step. A single slider scrubs through the log one step at a time.

Each hex with a city shows one of two things:
  - a colourless building icon (same glyph as hex_visualizer.py's
    draw_city_icon, in a neutral off-white) with the placing faction's
    number stamped on it, while its city is still unclaimed in the
    draft pool.
  - a faction-colored building icon, once that city has been drafted
    (or settled via the last-city/swap rule) as someone's capital.

A sidebar lists each faction's current placement and capital hex (or
"TBD" before they've drafted), same layout pattern as
hex_gen_visualizer.py's terrain-bag sidebar.
"""

import json
import os
import sys
import pygame

from hex_common import hex_to_pixel, hex_corner, compute_hex_size
from hex_visualizer import (
    TERRAIN_COLORS, HEX_OUTLINE_COLOR, BG_COLOR, TEXT_COLOR,
    SIDEBAR_BG_COLOR, SIDEBAR_DIVIDER_COLOR, FACTION_COLORS,
    draw_city_icon, Slider,
)

BOARD_AREA_W = 900
SIDEBAR_WIDTH = 260
WINDOW_W = BOARD_AREA_W + SIDEBAR_WIDTH
WINDOW_H = 900
MARGIN = 20
SLIDER_BAND_HEIGHT = 70

NEUTRAL_CITY_COLOR = (235, 235, 240)  # colourless/unclaimed - distinct from FACTION_COLORS[7]'s grey
NEUTRAL_LABEL_COLOR = (20, 20, 20)

STATE_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "city_placement_log.json")

_STEP_NARRATION = {
    "place": "Faction {f} places a colourless city",
    "draft": "Faction {f} drafts a city",
    "draft_auto": "Faction {f} gets their own city back (last city, no choice)",
    "keep": "Faction {f} keeps the leftover city (declines the swap)",
    "swap": "Faction {f} swaps with Faction {p} for their city",
}


def load_log(path):
    with open(path, "r") as f:
        data = json.load(f)
    terrain_map = {}
    for key, terrain in data["terrain"].items():
        q, r, s = (int(x) for x in key.split("_"))
        terrain_map[(q, r, s)] = terrain
    return data["radius"], data["num_factions"], terrain_map, data["steps"]


def compute_state(steps, upto):
    """(hex_info, faction_placed, faction_capital) as of step `upto`
    (0 = nothing has happened yet). hex_info: {(q,r,s): {"kind": "placed",
    "placer": f} or {"kind": "owned", "faction": f}}. faction_placed/
    faction_capital: {faction: (q,r,s)}, capital only present once
    drafted/settled."""
    hex_info = {}
    faction_placed = {}
    faction_capital = {}

    def own(coord, faction):
        hex_info[coord] = {"kind": "owned", "faction": faction}
        faction_capital[faction] = coord

    for step in steps[:upto]:
        coord = (step["q"], step["r"], step["s"])
        t = step["type"]
        f = step["faction"]
        if t == "place":
            hex_info[coord] = {"kind": "placed", "placer": f}
            faction_placed[f] = coord
        elif t in ("draft", "draft_auto", "keep"):
            own(coord, f)
        elif t == "swap":
            own(coord, f)
            own((step["placer_q"], step["placer_r"], step["placer_s"]), step["placer_faction"])

    return hex_info, faction_placed, faction_capital


def draw_hex(surface, center, size, terrain, info, font):
    points = [hex_corner(center, size, i) for i in range(6)]
    pygame.draw.polygon(surface, TERRAIN_COLORS[terrain], points)
    pygame.draw.polygon(surface, HEX_OUTLINE_COLOR, points, width=1)

    if info is None:
        return

    cx, cy = center
    city_center = (cx, cy - size * 0.62 + 4)
    if info["kind"] == "owned":
        draw_city_icon(surface, city_center, FACTION_COLORS[info["faction"]])
    else:
        draw_city_icon(surface, city_center, NEUTRAL_CITY_COLOR)
        label_surf = font.render(str(info["placer"]), True, NEUTRAL_LABEL_COLOR)
        surface.blit(label_surf, label_surf.get_rect(center=city_center))


def draw_status_sidebar(surface, x0, y0, width, height, num_factions,
                         faction_placed, faction_capital, header_font, row_font):
    pygame.draw.rect(surface, SIDEBAR_BG_COLOR, pygame.Rect(x0, y0, width, height))

    pad = 16
    header_surf = header_font.render("Capital Setup", True, TEXT_COLOR)
    surface.blit(header_surf, (x0 + pad, y0 + pad))

    row_h = 52
    list_top = y0 + pad + 34
    for f in range(num_factions):
        row_top = list_top + f * row_h
        if f > 0:
            pygame.draw.line(surface, SIDEBAR_DIVIDER_COLOR,
                              (x0 + pad, row_top), (x0 + width - pad, row_top), width=1)

        swatch = pygame.Rect(x0 + pad, row_top + 4, 14, 14)
        pygame.draw.rect(surface, FACTION_COLORS[f], swatch)
        header_surf = row_font.render(f"Faction {f}", True, TEXT_COLOR)
        surface.blit(header_surf, (swatch.right + 8, row_top))

        placed = faction_placed.get(f)
        capital = faction_capital.get(f)
        placed_text = f"Placed: {placed}" if placed else "Placed: -"
        capital_text = f"Capital: {capital}" if capital else "Capital: TBD"
        surface.blit(row_font.render(placed_text, True, TEXT_COLOR), (x0 + pad, row_top + 20))
        surface.blit(row_font.render(capital_text, True, TEXT_COLOR), (x0 + pad, row_top + 36))


def main():
    if not os.path.exists(STATE_FILE):
        print(f"Could not find {STATE_FILE}")
        print("Run run.py first to create it.")
        sys.exit(1)

    radius, num_factions, terrain_map, steps = load_log(STATE_FILE)
    coords = list(terrain_map.keys())

    pygame.init()
    screen = pygame.display.set_mode((WINDOW_W, WINDOW_H))
    pygame.display.set_caption("City Placement / Draft Visualizer")
    clock = pygame.time.Clock()

    board_area_h = WINDOW_H - SLIDER_BAND_HEIGHT
    size = compute_hex_size(radius, BOARD_AREA_W, board_area_h, MARGIN)
    label_font = pygame.font.SysFont("arial", 16)
    sidebar_header_font = pygame.font.SysFont("arial", 17, bold=True)
    sidebar_row_font = pygame.font.SysFont("arial", 14)
    city_label_font = pygame.font.SysFont("arial", 11, bold=True)

    raw_centers = {coord: hex_to_pixel(coord[0], coord[1], size) for coord in coords}
    xs = [p[0] for p in raw_centers.values()]
    ys = [p[1] for p in raw_centers.values()]
    board_cx = (min(xs) + max(xs)) / 2
    board_cy = (min(ys) + max(ys)) / 2
    offset_x = BOARD_AREA_W / 2 - board_cx
    offset_y = board_area_h / 2 - board_cy
    centers = {coord: (p[0] + offset_x, p[1] + offset_y) for coord, p in raw_centers.items()}

    def label_fn(i):
        if i == 0:
            return f"Step 0 / {len(steps)}   (before setup)   (drag, or use ←/→)"
        step = steps[i - 1]
        text = _STEP_NARRATION[step["type"]].format(f=step["faction"], p=step.get("placer_faction"))
        return f"Step {i} / {len(steps)}   {text}   (drag, or use ←/→)"

    slider = Slider(WINDOW_W, WINDOW_H - 30, len(steps) + 1, label_fn)

    current_step = len(steps)  # start fully settled; scrub back to replay
    running = True
    dragging = False
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key in (pygame.K_LEFT, pygame.K_a):
                    current_step = max(0, current_step - 1)
                elif event.key in (pygame.K_RIGHT, pygame.K_d):
                    current_step = min(len(steps), current_step + 1)
            elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                if slider.hit_test(event.pos):
                    dragging = True
                    current_step = slider.index_at(event.pos[0])
            elif event.type == pygame.MOUSEBUTTONUP and event.button == 1:
                dragging = False
            elif event.type == pygame.MOUSEMOTION and dragging:
                current_step = slider.index_at(event.pos[0])

        hex_info, faction_placed, faction_capital = compute_state(steps, current_step)

        screen.fill(BG_COLOR)
        for coord, terrain in terrain_map.items():
            draw_hex(screen, centers[coord], size, terrain, hex_info.get(coord), city_label_font)

        draw_status_sidebar(screen, BOARD_AREA_W, 0, SIDEBAR_WIDTH, board_area_h, num_factions,
                             faction_placed, faction_capital, sidebar_header_font, sidebar_row_font)

        slider.draw(screen, current_step, label_font)

        pygame.display.flip()
        clock.tick(30)

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()
